package fr.valle.report_generator
package customexceptions

class DataFileNotFoundException(filePath: String, val cause: Option[Throwable] = None)
  extends Exception(String.format("Le fichier de donn√©es %s est introuvable.", filePath)) {
  initCause(cause.orNull)
}
